# Generated by Django 5.2.5 on 2025-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='The name of the file', max_length=500)),
                ('s3url', models.CharField(help_text='The Amazon S3 url of the file', max_length=500)),
            ],
        ),
    ]
