# Generated by Django 5.2.5 on 2025-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='s3url',
        ),
        migrations.AddField(
            model_name='file',
            name='diskname',
            field=models.CharField(default='default-diskname', help_text='The on disk uuid name of the file', max_length=36),
            preserve_default=False,
        ),
    ]
