# Generated by Django 5.2.5 on 2025-08-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_s3url_file_diskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='diskname',
            field=models.CharField(help_text='The on disk uuid name of the file', max_length=537),
        ),
    ]
